### PR TITLE
Update site.conf

### PR DESCRIPTION
**Pull request by heini66**
adapt mtu to match bat 15

### CODE REVIEW

**Comment by rubo77** [comment]
You cannot adapt the MTU just like that. You would have to change the port as well and serve both fastd-connections on different ports for nodes that are stil not updated to the new fastd settings.

also it is not sure, that the Kabel Deutschland Problem in SH is gone with Batman 15

**Comment by knoxia** [comment]
In addition. We use 1280 as MTU because it is the minimum frame size for ipv6 bat 15 packages. This allows us to run Freifunk on every isp line.

The problem with kdg is broken hw selled by kdg. The cable modem isnt able to route 1280 frames correcly.

**Comment by Tarnatos** [comment]
In addition. We use 1280 as MTU because it is the minimum frame size for ipv6 bat 15 packages. This allows us to run Freifunk on every isp line.

The problem with kdg is broken hw selled by kdg. The cable modem isnt able to route 1280 frames correcly.

**Comment by rubo77** [comment]
The cable modem isnt able to route larger than 1370 frames correcly.

But we decided to use the minimum possible.

Maybe the minimum for ip6 could be 1300. I am not sure, if we'll have a problem then?

**Pull request closed without merging**
