### PR TITLE
SSID with http://

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by sargon** [comment]
On the first ffnordcon this year (2015) we talked about a suggestion for community SSID's, the suggestion said a SSID should be of form "<town>.freifunk.net". When I'm remembering correctly we voted against the urilasation of those string, because of the string length usual mobile clients display when it comes to SSID's. So the protocol descriptor may lead to a hidden base part of the SSID.

That in mind I vote against this pr.

**Comment by rubo77** [comment]
I thought the display length is only a problem with long community names. I have never seen a display not showing the "freifunk" in "http://kiel.freifunk.net/".

I like the http:// so the visitors are more aware of the nature of the SSID being a link to visit.

And I see no reason, why we should use a german wide convention, so **in short community names** the http:// is really helping

**Comment by Tarnatos** [comment]
I would prefer just Freifunk!

**Comment by rubo77** [comment]
the problem with just "Freifunk" is that different communities, that use the same SSID do not roam and if there are several different communities in the same street, the clients do not notice the change and roaming is really broken

Different networks should not use the same SSID!

**Comment by do9xe** [comment]
As the RFC for a Wireless LAN SSID is saying, that every Layer2-Network needs its own, individual SSID we should NOT choose Freifunk.
As sargon said: at the ffnord-con we decided on non-url ssid's an to stick with the freifunk-interal "RFC" for SSID's an so we will stay at "nord.freifunk.net"

**Pull request closed without merging**
